@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lofimodding.gradient.advancements.criterion;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
