# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/lo-fi-modding/gradient/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="gradient" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Gradient" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#TODO updateJSONURL="https://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/lo-fi-modding/gradient" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#TODO logoFile="gradient.png" #optional
# A text field displayed in the mod UI
credits="Corey Frenette (Monoxide)" #optional
# A text field displayed in the mod UI
authors="Corey Frenette" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A long-term technological progression mod.
'''
[[dependencies.gradient]]
  modId="forge"
  mandatory=true
  versionRange="[31.2,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.gradient]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.15.2]"
  ordering="NONE"
  side="BOTH"
[[dependencies.gradient]]
  modId="terra"
  mandatory=true
  versionRange="[1.15.2-1.0.0,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.gradient]]
  modId="progression"
  mandatory=true
  versionRange="[1.15.2-1.0.0,)"
  ordering="NONE"
  side="BOTH"
