@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lofimodding.gradient.containers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
