@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lofimodding.gradient.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
