@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lofimodding.gradient.entities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
