@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package lofimodding.gradient.advancements;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
